//Creating an object and exporting it:
module.exports = {
    posts: [],

    getAll(){
        return this.posts;
    },

    newPost(title, description){
        this.posts.push({id: generateID(), title: title, description: description});
    },

    del(id){
        let index = this.searchIndex(id);
        this.posts.splice(index, 1);

        
    },

    searchIndex(id){
        for(i in this.posts){
            if(this.posts[i].id == id){
                return i;
            }
        }
    }
}

//In the meantime, the ID will be generated by a specific function.
//Then, it will be created with MongoDB.
function generateID(){
    //return Math.random().toString(36); //the '36' means that it could have all the alphabet (26), and all the numbers(0-9)
    //example of result: 0.9p6x4awi17

    // the "a" is necessary, because it was giving an error that if the id started with a number, it was not deleted then.
    return "a" + Math.random().toString(36).substring(2,9); //it will start at the second index (position 3), i.e, the result won't have the '0.'. The ID will be a integer (as String).

}